// Module included in the following assemblies:
//
// * cli_reference/rosa_cli/get-started-with-rosa.adoc

[id="rosa-configure_{context}"]
= Configure rosa

Use the following commands to configure `rosa`.

[id="rosa-login_{context}"]
== rosa login

Log in to your Red Hat account, saving the credentials to the `rosa` configuration file. You must provide a token when logging in. You can copy your token by from link:https://cloud.redhat.com/openshift/token/moa[the {product-title} token page].

[source,terminal]
----
$ rosa login
----

`rosa` will look for a token in the following priority order:

* command-line flags
* The `MOA_TOKEN` environment variable
* The `rosa` configuration file
* Interactively from a command-line prompt

[id="rosa-logout_{context}"]
== rosa logout

Log out of `rosa`. Logging out removes the `rosa` configuration file.

[source,terminal]
----
$ rosa logout
----

[id="rosa-verify-permissions_{context}"]
== rosa verify permissions

Verify the AWS permissions required to create a `rosa` cluster are configured correctly.

[source,terminal]
----
$ rosa verify permissions
----

[id="rosa-verify-quota_{context}"]
== rosa verify quota

Verify the AWS quota required to create a cluster is available in your AWS account.

[source,terminal]
----
$ rosa verify quota
----

[id="rosa-verify-ocp-client_{context}"]
== rosa verify openshift-client

Verify the OpenShift Container Platform command-line interface (`oc`) is installed correctly.

[source,terminal]
----
$ rosa verify openshift-client
----

[id="rosa-download-ocp-client_{context}"]
== rosa download openshift-client

Download the OpenShift Container Platform command-line interface (`oc`).

[source,terminal]
----
$ rosa download openshift-client
----

After downloading `oc`, you must unzip the archive and add it to your path.